### ISSUE TITLE
no live?

### ISSUE THREAD

**Issue by ledfn** [BaseballTheater/BaseballTheater#118]
where is the live section?

**Comment by jakelauer** [comment]
Hi! The live section is only present in games that are currently being played. When games are over (or before they begin), that tab isn't present. The 'Plays' tab contains all of that same information after a game is over.

**Comment by ledfn** [comment]
I guess the game had just gotten over because it showed bottom 9 0-outs and the live section wasn't available. Probably just some delay in the system (I don't know what I'm talking about)? Even the "plays" section was only up to the end of the top of the 9th.

Nbd, I thought I was trippin lol
