### ISSUE TITLE
Chicago White Sox appear twice in Favorite Team dropdown selection

### ISSUE THREAD

**Issue by i5hine** [BaseballTheater/BaseballTheater#16]
![bt](https://user-images.githubusercontent.com/34467897/75703818-3737d380-5c86-11ea-978f-5967b6e05e7e.JPG)

**Comment by hellocontrol-bng** [comment]
That's weird. As a Cubs fan, I apologize. Of all the teams to show up twice!

**Comment by jakelauer** [comment]
That's weird. As a Cubs fan, I apologize. Of all the teams to show up twice!
