### ISSUE TITLE
Copyright shows up out of place on mobile

### ISSUE THREAD

**Issue by double-dose-larry** [BaseballTheater/BaseballTheater#20]
![Screenshot_20200302-214235_Chrome](https://user-images.githubusercontent.com/52589974/75738031-32e3d880-5ccf-11ea-980b-b178e0d04394.jpg)

On chrome and duckduckgo on android

**Comment by jakelauer** [comment]
Fixed by https://github.com/jakelauer/BaseballTheater/commit/9d2b2f60424464e9d693c10f6a1754f72fe4eacc
