### ISSUE TITLE
Repeats in the home run section

### ISSUE THREAD

**Issue by double-dose-larry** [BaseballTheater/BaseballTheater#25]
![image](https://user-images.githubusercontent.com/52589974/76178110-b0568f80-618c-11ea-9024-cdfec961f129.png)

homerun highlights have repeats.

not sure if it matters but here's the url

https://baseball.theater/search/home_run/606286%252C603965%252C604354%252C605900%252C604545%252C607098%252C616615%252C605609%252C604257%252C604161%252C605996%252C606381%252C605414%252C606479%252C606189%252C605511%252C606576%252C604063

**Comment by double-dose-larry** [comment]
Just checked today and it seems to getting worse? Instead of two cards with the same highlight, I'm now seeing 4 or more.

**Comment by jakelauer** [comment]
I think there's a big in the logic that loads the searchable data into memory, which is bad because not only will you see duplicates, but also because it's a memory leak. I'll get it fixed as soon as I can!
