### ISSUE TITLE
HockeyTheater

### ISSUE THREAD

**Issue by goldenpipes** [BaseballTheater/BaseballTheater#3]
I know the NHL uses MLB systems for online streaming and such. Would it be possible to do this for hockey?

Cheers!

**Comment by hellocontrol-bng** [comment]
It's possible! I will look into it. If you could link me to a couple of example videos from game highlights or something, that would help!

**Comment by jakelauer** [comment]
It's possible! I will look into it. If you could link me to a couple of example videos from game highlights or something, that would help!

**Comment by goldenpipes** [comment]
https://www.nhl.com/video/crawford-earns-first-star-of-week/t-283272962/c-54287903

**Comment by Jessicachong** [comment]
#3

**Comment by Jessicachong** [comment]
#3

**Comment by jakelauer** [comment]
Going to close this at this time. BT is taking up all the time I have to work on stuff like this and has a lot of baseball-specific enhancements.
