### ISSUE TITLE
SO AWESOME!

### ISSUE THREAD

**Issue by goldenpipes** [BaseballTheater/BaseballTheater#4]
Great work Jake!

BEST BASEBALL APP/SITE EVER!

is there a way to webhook from your site to discord? just curious. I am an admin on the MN Twins discord server and it would be sweet if i could have a bot get the link and post them to the server. as it stands now i just copy the urls and paste them in.

Cheers!

**Comment by Jessicachong** [comment]
#4

**Comment by Jessicachong** [comment]
#4

**Comment by jakelauer** [comment]
Thanks! Sorry I missed this forever ago - wasn't checking the issues :) If you are still interested in this, let me know.
