### ISSUE TITLE
search = broken

### ISSUE THREAD

**Issue by grand-lotus-iroh** [BaseballTheater/BaseballTheater#48]
if i click search on desktop browser i get invalid date error.

![1fc-4u4](https://user-images.githubusercontent.com/1291364/115921819-0a2a1f80-a44a-11eb-9ecb-54e0218ad6bf.gif)

**Comment by double-dose-larry** [comment]
Experiencing the same issue on Firefox 89 on Windows

**Comment by jakelauer** [comment]
Fixed

**Comment by grand-lotus-iroh** [comment]
thanks for fixing this. i might start using the website again.
