### ISSUE TITLE
Suggestion: show inning on in progress games

### ISSUE THREAD

**Issue by DanLauer** [BaseballTheater/BaseballTheater#55]
The app is so beautiful and smooth now. Glad to have standings. Box score formatting is beautiful. LOVE THE APP AND I'M IN IT MULTIPLE TIMES A DAY.

One thing I would love in games view is to see "Top 7" or similar either in place of or next to "In Progress" for active games. Or "Top 7, 1 out, 2 on".

Thanks for this gem, Control.

**Comment by jakelauer** [comment]
Done!
