### ISSUE TITLE
Pre-2019 Videos not available?

### ISSUE THREAD

**Issue by impressivewebs** [BaseballTheater/BaseballTheater#59]
I don't see this mentioned in any of the closed issues, so forgive me if it's already been discussed, but are there plans to get the pre-2019 videos linked again? If I try to view videos for any game in 2018 or earlier it says "This game has no videos available yet." I know MLB has changed the way videos are accessed via their data, so maybe that has something to do with it.

Thanks for making this site/app, it's a great way to look up highlights.

**Comment by jakelauer** [comment]
A bit ago, the MLB API changed the way they returned highlights, and that way does not return the older ones. Since we use their API to get data, the older videos disappeared from here as well. However, you may be able to find some highlights from past years on the Search page by including that year in the search.

**Comment by impressivewebs** [comment]
@jakelauer Yeah, that's what I figured. Is there no old API for the old highlights? Is it not possible to essentially fork the code to use the old API? Or are those videos not even available via any API?

And thanks for pointing out the search feature, I had never tried that before, that seems to work fairly well when you add the year to the search (though it does seem to only bring up low res videos).

**Comment by jakelauer** [comment]
Unfortunately, they retired the old API (which was really just XML files). They also removed access to some of those old videos anyway, which sucks. It's not an official API, so there's really no reason for them to keep anything around that they don't use themselves, so I get it. But it would be nice!
