### ISSUE TITLE
Mobile App causes longer videos to have audio/video of highlights to be out of sync

### ISSUE THREAD

**Issue by JDubled** [BaseballTheater/BaseballTheater#61]
When watching a longer video such as the game recap or main highlights, the audio and video can get out of sync in the middle of the video. This issue occurs on both the iOS mobile app, and the Safari version

Also, viewing on iOS Safari, after watching one video and viewing another, the first video opens again

iOS version 14.7.1
Both Safari and the “Mobile App” or add to home screen option

**Comment by jakelauer** [comment]
Videos are handled by the device browser. Baseball theater has no control over this.

**Comment by JDubled** [comment]
Ok, understood, thank you so much for the site and your work on this, it’s all much appreciated!
