### ISSUE TITLE
Game buttons shuffle themselves repeatedly on mouseover - Firefox 92

### ISSUE THREAD

**Issue by infinitenines** [BaseballTheater/BaseballTheater#64]
Moving the mouse cursor over the box score preview buttons on the main page (//baseball.theater/games/[date]) causes the game day link and contents to shuffle themselves repeatedly at a high rate of speed. 

The behavior impacts the pages FPS, increases CPU usage, and RAM utilization will increase until the tab is closed or mouse is moved from the button limits.

Video of the behavior: https://streamable.com/vmfdl5

**Comment by xytroyzy** [comment]
For me this happens on Firefox 92.0 on both Windows and OSX on a clean profile with no extensions active. Chrome is not affected.

**Comment by jakelauer** [comment]
Fixed!
