### ISSUE TITLE
Entire page is glitching, baseball.theater has become unusable

### ISSUE THREAD

**Issue by yucandu** [BaseballTheater/BaseballTheater#67]
After one of the most recent updates, baseball.theater has become unusable.  I can't click on anything.  The moment the mouse hovers over any of the available games, the entire page starts flashing and jittering.  Here is a video record:

https://streamable.com/n0ebyh

Browser is up to date firefox.  Plugins include Ublock Origin, Dark Reader, and Netflix IMDB Scores.  PC is up to date Windows 10.  Disabling all plugins and running in Private Firefox Window, issue still persists.

Issue does NOT seem to exist in latest Chromium-based version of Microsoft Edge.  Only Firefox.

**Comment by jakelauer** [comment]
Fixed!
