### ISSUE TITLE
Time zone/time inaccurate

### ISSUE THREAD

**Issue by xytroyzy** [BaseballTheater/BaseballTheater#7]
I'm in HST. baseball.theater shows the time for all games in Eastern Time, although the string says HST.
Fro example, a game starting at 8:05 Eastern displays as '8:05 PM HST'

This was working correctly last year. I remember because tz stuff is hard and that was a nice feature.

Same behavior on all my browsers.

**Comment by jakelauer** [comment]
Closing this as I have published the new version. If this still occurs, let me know.
