### ISSUE TITLE
Are June and July games suddenly not available?

### ISSUE THREAD

**Issue by wh323** [BaseballTheater/BaseballTheater#91]
Spot checked a few dates starting with June 7. Thank you.

**Comment by hellocontrol-bng** [comment]
Looks okay to me? 

![F3F1A006-B716-4E13-B55B-CC6ADA205E97](https://user-images.githubusercontent.com/31326215/184048102-0225b1fc-df61-4a8e-8cff-09e235b54c34.png)

**Comment by wh323** [comment]
The page looks fine. Then when I click on a game, I get

This game has no videos available yet.

**Comment by jakelauer** [comment]
The details showing depend on what the MLB Gameday API returns. If no videos are showing, MLB must have removed them.

**Comment by jakelauer** [comment]
Today I pushed a fix for times MLB removes the videos from games. You should now be able to go back to those games and see results!
