### ISSUE TITLE
Patreon Login Not Working

### ISSUE THREAD

**Issue by mdrews93** [BaseballTheater/BaseballTheater#97]
Hey there,

I just subscribed via Patreon, but I'm unable to login. I've tried on Brave (Version 1.35.104 Chromium: 98.0.4758.109 (Official Build) (x86_64)) and on Safari (Version 15.4 (17613.1.17.1.13)) as well as on Brave on my Android phone. If there's any further diagnostic information you need, I can provide whatever you need.

**Comment by jakelauer** [comment]
Can you give more details about what happens when you try?

**Comment by jakelauer** [comment]
Fixed!
