### ISSUE TITLE
Issues going back when on /game route

### ISSUE THREAD

**Issue by gregostrowski** [BaseballTheater/BaseballTheater#98]
When on a game page (ie `https://baseball.theater/game/_/662604/Highlights`), I am unable to go back to the `/games` page that I was previously on. However, the history between tabs in the `/game` route works (ie Highlights => box score => go back). I don't remember this issue being present last week. 

Tested in Chrome 104.0.5112.102

To Recreate:
1. create new tab
2. visit baseball.theater
3. click on any game thread
4. click back button in browser (or history.back() in console)

Or
1. create new tab
2. visit baseball.theater
3. click on Standings in the side nav
4. click back twice (should take you back to your empty tab, but we get suck on the homepage)

**Comment by jakelauer** [comment]
I see the same issue. Likely due to a behind-the-scenes upgrade I made to the site infrastructure. I'll check it out!

**Comment by jakelauer** [comment]
Fixed!
