### ISSUE TITLE
Can't finish patron login

### ISSUE THREAD

**Issue by DanLauer** [BaseballTheater/BaseballTheater#99]
I credential in and get this:
![Screenshot_20220827-200700](https://user-images.githubusercontent.com/2616544/187055796-ee6a3940-9331-4e25-bdb9-94a45aa54f4e.png)

Then I tap Allow and get this...forever:
![Screenshot_20220827-200723](https://user-images.githubusercontent.com/2616544/187055804-4b627d16-710c-488e-a430-8e9ba7cec6af.png)

I've tried 10-15 times over the past several days. Rebooted my phone at least twice.

Android 13/Pixel 6 Pro

**Comment by jakelauer** [comment]
Fixed!
